### ISSUE TITLE
kbm-robot doesn't stop after quiting in Linux

### ISSUE THREAD

**Issue by Uriziel** [waylaidwanderer/DotaBuddy#11]
It also consumes 100% CPU.

**Comment by Uriziel** [comment]
Also starts despite steam integration being disabled.

**Comment by waylaidwanderer** [comment]
I'm looking into alternatives for emulating mouse/keyboard. Was using robotjs but it was buggy.

**Comment by waylaidwanderer** [comment]
I made DotaBuddy explicitly stop kbm-robot after closing. https://github.com/waylaidwanderer/DotaBuddy/commit/02dd2258679bbc8dfc2e2481d2f3fd0ee78cfefc#diff-ff989c59c19d65197d0fca48718470cdR18

If it doesn't work let me know.
